path:
    local: ../fixtures/local
    std: ../fixtures/std/processor-tests/humans
    src: ../src
    locale: ../locale
    modules: ../juris-modules
    styletests: ../fixtures/style
    jing: ../jing/jing-20131210.jar
    cslschema: ../csl-schemata/csl/csl.rnc
    cslmschema: ../csl-schemata/csl-m/csl-mlz.rnc